version: "3.8"

services:
    placegram:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        restart: always
        networks:
            - placegram-frontend

networks:
    placegram-frontend:
        driver: bridge
